### ISSUE TITLE
CUDA 11.2 version in .env file should be 11.2.0

### ISSUE THREAD

**Issue by jrhemstad** [trxcllnt/rapids-compose#48]
When selecting CUDA 11.2 as the rapids compose version, it will generate a `.env` file like:
```
CUDA_VERSION=11.2
CONDA_CUDA_TOOLKIT_VERSION=11.2
```

However, this will fail as it claims to not be able to find 11.2 docker container/packages.

It should be:
```
CUDA_VERSION=11.2.0
CONDA_CUDA_TOOLKIT_VERSION=11.2.0
```

**Comment by trxcllnt** [comment]
`CONDA_CUDA_TOOLKIT_VERSION` has to stay `11.2` _without_ the patch, because the way our libs [depend on the `cudatoolkit`](https://github.com/rapidsai/cudf/blob/4d6ecd12cac6856e5d45fe96891e490d658a24be/conda/recipes/cudf/meta.yaml#L49):
```
- {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
```

`max_pin=x.x` means "pin to the latest version of cudatoolkit for the given `MAJOR.MINOR` version, and nothing less."

For example, if the latest CUDA 11.2 in conda is `cudatoolkit=11.2.72`, conda will fail to resolve the environment if we tell it to install `cudatoolkit=11.2.0`.
