### ISSUE TITLE
Add VSCode workspace configuration for clang-format

### ISSUE THREAD

**Issue by jrhemstad** [trxcllnt/rapids-compose#9]
The compose VSCode workspace should install the `clang-format` extension and point it to the conda `clang-format` executable.

Consider also enabling the `formatOnSave` by default.

**Comment by trxcllnt** [comment]
Added the former two things in commit https://github.com/trxcllnt/rapids-compose/commit/790ebbc4af4bee4e80222acbddb545326fde1800. I left `formatOnSave` undefined because it could bother some people, and there wouldn't be any way to override because the workspace-specific settings take precedence over the global user settings.
